CREATE DATABASE APPDOMAINPROJECT
USE APPDOMAINPROJECT

CREATE TABLE USERACCOUNT(
FNAME				VARCHAR(30)		NOT NULL,
LNAME				VARCHAR(30)		NOT NULL,
EMAIL				VARCHAR(50)		NOT NULL UNIQUE,
B_MONTH				CHAR(2)			NOT NULL,
B_DAY				CHAR(2)			NOT NULL,
B_YEAR				CHAR(4)			NOT NULL,
USERNAME			VARCHAR(30)		NOT NULL PRIMARY KEY,
PASSWORD			VARCHAR(30)		NOT NULL,
LOGINTIME			DATETIME,
SIGNUPTIME			DATE,
QUESTION1			VARCHAR(50)		NOT NULL,
ANSWER1				VARCHAR(50)		NOT NULL,
QUESTION2			VARCHAR(50)		NOT NULL,
ANSWER2				VARCHAR(50)		NOT NULL,
QUESTION3			VARCHAR(50)		NOT NULL,
ANSWER3				VARCHAR(50)		NOT NULL,
)


INSERT INTO USERACCOUNT(FNAME, LNAME, EMAIL, B_MONTH, B_DAY, B_YEAR, USERNAME, PASSWORD, APPROVALDATE, QUESTION1,
ANSWER1, QUESTION2, ANSWER2, QUESTION3, ANSWER3) VALUES
('Iram', 'Nawaz', 'admin@gmail.com', '08','16','1996', 'inawaz0618', 'admin2021!', '20190618 10:34:09 AM', 
'What position are you?','admin','What was the color of your first car?','White','What is your mothers maiden name?','Nawaz')


INSERT INTO USERACCOUNT(FNAME, LNAME, EMAIL, B_MONTH, B_DAY, B_YEAR, USERNAME, PASSWORD, APPROVALDATE, QUESTION1,
ANSWER1, QUESTION2, ANSWER2, QUESTION3, ANSWER3) VALUES
('Duy', 'Nguyen', 'manager@gmail.com', '06','11','1998', 'dnguyen0220', 'manager2021!', '20200214 12:19:48 PM', 
'What position are you?','manager','What was the color of your first car?','White','What is your mothers maiden name?','Nguyen')


INSERT INTO USERACCOUNT(FNAME, LNAME, EMAIL, B_MONTH, B_DAY, B_YEAR, USERNAME, PASSWORD, APPROVALDATE, QUESTION1,
ANSWER1, QUESTION2, ANSWER2, QUESTION3, ANSWER3) VALUES
('Ashley', 'Lowe', 'user1@gmail.com', '11','04','1999', 'alowe1220', 'user2021!', '20201212 05:35:05 PM', 
'What position are you?','user','What was the color of your first car?','White','What is your mothers maiden name?','Lowe')



SELECT COUNT(USERNAME) AS countID, DATEDIFF(mi,LOGINTIME,GETDATE ( )) AS TimeElapsed
FROM FailedLogins
WHERE (USERNAME = '#username#')
    AND DATEDIFF(mi,LOGINTIME,GETDATE ( )) <= 30
GROUP BY USERNAME, LOGINTIME
HAVING COUNT(LoginID) >= 3;