CREATE DATABASE APPDOMAINPROJECT
USE APPDOMAINPROJECT

CREATE TABLE LOGIN(
USERNAME			VARCHAR(20)		NOT NULL PRIMARY KEY,
PASSWORD			VARCHAR(10)		NOT NULL,
LOGINTIME			DATETIME,
)

CREATE TABLE SIGNUP(
FNAME				VARCHAR(30)		NOT NULL,
LNAME				VARCHAR(30)		NOT NULL,
EMAIL				VARCHAR(50)		NOT NULL UNIQUE,
B_MONTH				CHAR(2)			NOT NULL,
B_DAY				CHAR(2)			NOT NULL,
B_YEAR				CHAR(4)			NOT NULL,
) 

CREATE TABLE FORGOTPASSWORD(
USERNAME			VARCHAR(20)		NOT NULL PRIMARY KEY,
EMAIL				VARCHAR(50)		NOT NULL UNIQUE,
)

CREATE TABLE RESETPASSWORD(
PASSWORD			VARCHAR(10),
NEWPASSWORD			VARCHAR(10)		NOT NULL,
)

CREATE TABLE SECURITYQ(
QUESTION1			VARCHAR(50)		NOT NULL,
ANSWER1				VARCHAR(50)		NOT NULL,
QUESTION2			VARCHAR(50)		NOT NULL,
ANSWER2				VARCHAR(50)		NOT NULL,
QUESTION3			VARCHAR(50)		NOT NULL,
ANSWER3				VARCHAR(50)		NOT NULL,
)




SELECT COUNT(USERNAME) AS countID, DATEDIFF(mi,LOGINTIME,GETDATE ( )) AS TimeElapsed
FROM FailedLogins
WHERE (USERNAME = '#username#')
    AND DATEDIFF(mi,LOGINTIME,GETDATE ( )) <= 30
GROUP BY USERNAME, LOGINTIME
HAVING COUNT(LoginID) >= 3;